<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Clarity1_2.ATS012AsatrusteewhohasmegeredhisaccountwithhismemberaccountplaceacalculationRequest"
           tests="2"
           failures="1"
           errors="0"
           skipped="0"
           time="18.838">
  <properties />
      <testcase name="tearDown" time="0.000">
            <failure type="java.lang.AssertionError"
                  message="java.lang.AssertionError: expected [true] but found [false]"
              >
<![CDATA[java.lang.AssertionError: java.lang.AssertionError: expected [true] but found [false]
  org.testng.Assert.fail(Assert.java:94)
  Clarity1_2.ATS012AsatrusteewhohasmegeredhisaccountwithhismemberaccountplaceacalculationRequest.tearDown(ATS012AsatrusteewhohasmegeredhisaccountwithhismemberaccountplaceacalculationRequest.java:75)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:483)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
  org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
  org.testng.internal.Invoker.invokeConfigurations(Invoker.java:216)
  org.testng.internal.Invoker.invokeConfigurations(Invoker.java:143)
  org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:115)
  org.testng.TestRunner.privateRun(TestRunner.java:746)
  org.testng.TestRunner.run(TestRunner.java:600)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
  org.testng.SuiteRunner.run(SuiteRunner.java:268)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
  org.testng.TestNG.runSuites(TestNG.java:1104)
  org.testng.TestNG.run(TestNG.java:1076)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
      </failure>

          </testcase>
  
  
      <testcase name="test0109ATS012AsatrusteewhohasmegeredhisaccountwithhismemberaccountplaceacalculationRequest" time="18.838" />
  
</testsuite>
